### ISSUE TITLE
Highlight matching brackets, braces and parentheses

### ISSUE THREAD

**Issue by ghost** [janusvm/nord-rstudio#2]
Love this Nord-based theme for my RStudio, thanks a lot for prividing us with it!
The only thing that's missing is highlighting matching brackets, braces and parentheses. 
For some reason this does not work for me when using your theme opposed to any other of the standard themes. Did you accidentally set it up with the background-color or not include it at all?
Thanks a lot, cheers

**Comment by ghost** [comment]
Managed to fix it myself, this was missing in the rstheme file:
```
.ace_bracket {
    margin: 0 !important;
    border: 0 !important;
    background-color: var(--nord11);
}
```

I am new to github but do you want me to create a pull request for this?

**Comment by janusvm** [comment]
Thank you very much! It's very likely I just forgot to include the brackets, because it sure is something I like to have myself too :)

A pull request would be nice yea

**Comment by ghost** [comment]
Just created the respective pull request, hope I did it correctly.
Will continue working with your theme and get back to you if something else comes to mind :)

Thanks again!
